artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_type: kaggle
  #kaggle_dataset_owner: mohamedhanyyy # if we are extracting from kaggle dataset
  #kaggle_dataset_name: chest-ctscan-images #if we are extracting from kaggle dataset
  kaggle_competition_name: rohlik-orders-forecasting-challenge
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/